server:
  port: 8888
spring:
  application:
    name: config-server


#get config github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vscGabriel/chat-conversation
          search-paths:
            - config
          skip-ssl-validation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka